name: Build sto26

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Create App Structure
        run: |
          mkdir -p Payload/sto26.app
          # Encontre o SDK do iPhone
          SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          clang -arch arm64e -isysroot $SDK \
            -framework UIKit \
            -framework Foundation \
            -framework MobileCoreServices \
            -o TrollInstallerTC ViewController.m
          cp TrollInstallerTC Payload/sto26.app/sto26
          cat <<EOF > Payload/sto26.app/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://apple.com">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key> <string>sto26</string>
              <key>CFBundleIdentifier</key> <string>com.trollstore.26</string>
              <key>CFBundleName</key> <string>sto26</string>
              <key>CFBundlePackageType</key> <string>APPL</string>
              <key>CFBundleShortVersionString</key> <string>1.0</string>
              <key>LSRequiresIPhoneOS</key> <true/>
              <key>MinimumOSVersion</key> <string>15.0</string>
              <key>CFBundleSupportedPlatforms</key> <array><string>iPhoneOS</string></array>
          </dict>
          </plist>
          EOF
            
      - name: Pack IPA
        run: |
          # O iOS exige que a pasta Payload seja zipada como .ipa
          zip -r sto26.ipa Payload
          echo "[+] IPA Catalyst-26 Gerado."

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sto-26-IPA
          path: sto26.ipa
